spring:
  application:
    name: msCloudGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: msclientes_route
        uri: lb://msclientes
        predicates:
          - Path=/clientes/**

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka